//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.5485
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class DetailsViewSample {
    
    /// <summary>
    /// form1 элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    /// <summary>
    /// DetailsView1 элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.DetailsView DetailsView1;
    
    /// <summary>
    /// ObjectDataSource1 элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ObjectDataSource ObjectDataSource1;
    
    /// <summary>
    /// LabelInsertMessage элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label LabelInsertMessage;
}
