//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.5485
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class _Default {
    
    /// <summary>
    /// Head1 элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlHead Head1;
    
    /// <summary>
    /// form1 элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    /// <summary>
    /// GridViewMemberUser элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.GridView GridViewMemberUser;
    
    /// <summary>
    /// ObjectDataSourceMembershipUser элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ObjectDataSource ObjectDataSourceMembershipUser;
    
    /// <summary>
    /// LoginStatus1 элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.LoginStatus LoginStatus1;
    
    /// <summary>
    /// GridViewRole элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.GridView GridViewRole;
    
    /// <summary>
    /// CheckBoxShowRolesAssigned элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.CheckBox CheckBoxShowRolesAssigned;
    
    /// <summary>
    /// ButtonCreateNewRole элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button ButtonCreateNewRole;
    
    /// <summary>
    /// TextBoxCreateNewRole элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.TextBox TextBoxCreateNewRole;
    
    /// <summary>
    /// PanelCreateUser элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel PanelCreateUser;
    
    /// <summary>
    /// Label3 элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label Label3;
    
    /// <summary>
    /// TextBoxUserName элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.TextBox TextBoxUserName;
    
    /// <summary>
    /// Label4 элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label Label4;
    
    /// <summary>
    /// TextBoxPassword элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.TextBox TextBoxPassword;
    
    /// <summary>
    /// Label5 элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label Label5;
    
    /// <summary>
    /// TextBoxPasswordQuestion элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.TextBox TextBoxPasswordQuestion;
    
    /// <summary>
    /// Label6 элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label Label6;
    
    /// <summary>
    /// TextBoxPasswordAnswer элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.TextBox TextBoxPasswordAnswer;
    
    /// <summary>
    /// Label2 элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label Label2;
    
    /// <summary>
    /// TextBoxEmail элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.TextBox TextBoxEmail;
    
    /// <summary>
    /// Label9 элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label Label9;
    
    /// <summary>
    /// CheckboxApproval элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.CheckBox CheckboxApproval;
    
    /// <summary>
    /// ButtonNewUser элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button ButtonNewUser;
    
    /// <summary>
    /// LabelInsertMessage элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label LabelInsertMessage;
    
    /// <summary>
    /// ObjectDataSourceRoleObject элемент управления.
    /// </summary>
    /// <remarks>
    /// Автоматически создаваемое поле.
    /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ObjectDataSource ObjectDataSourceRoleObject;
}
